<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.jxust.ligongmall</groupId>
    <artifactId>ligong</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>ligong</name>
    <description>聚合项目</description>

    <modules>
        <module>ligong-coupon</module>
        <module>ligong-member</module>
        <module>ligong-order</module>
        <module>ligong-product</module>
        <module>ligong-ware</module>
    </modules>


</project>
